CREATE TABLE processed_events (
    event_id UUID PRIMARY KEY,
    machine_code VARCHAR(50) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_code VARCHAR(50) NOT NULL REFERENCES machines(code),
    anomaly_type VARCHAR(30) NOT NULL CHECK (anomaly_type IN ('HIGH_TEMPERATURE', 'HIGH_VIBRATION')),
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('WARNING', 'CRITICAL')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')),
    observed_value DOUBLE PRECISION NOT NULL,
    threshold_value DOUBLE PRECISION NOT NULL,
    unit VARCHAR(10) NOT NULL,
    health_score INTEGER NOT NULL CHECK (health_score BETWEEN 0 AND 100),
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    occurrence_count BIGINT NOT NULL CHECK (occurrence_count > 0),
    latest_event_id UUID NOT NULL REFERENCES processed_events(event_id),
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    resolution_note VARCHAR(2000)
);

-- Event uniqueness and incident uniqueness solve two different problems.
CREATE UNIQUE INDEX uk_alerts_active_incident ON alerts(machine_code, anomaly_type)
    WHERE status <> 'RESOLVED';
CREATE INDEX ix_alerts_machine_time ON alerts(machine_code, last_seen_at DESC);

CREATE TABLE alert_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id BIGINT NOT NULL REFERENCES alerts(id),
    action VARCHAR(30) NOT NULL CHECK (action IN ('CREATED', 'UPDATED', 'ACKNOWLEDGED', 'RESOLVED', 'STALE_IGNORED')),
    actor VARCHAR(100) NOT NULL,
    event_id UUID REFERENCES processed_events(event_id),
    correlation_id UUID,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    note VARCHAR(2000)
);
CREATE INDEX ix_alert_audit_alert ON alert_audit(alert_id, id);
